/*
 * Kubermatic API.
 *
 * Kubermatic API  This describes possible operations which can be made against the Kubermatic API.
 *
 * API version: 2.2.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package client

type AwsCloudSpec struct {

	AccessKeyId string `json:"accessKeyId,omitempty"`

	AvailabilityZone string `json:"availabilityZone,omitempty"`

	InstanceProfileName string `json:"instanceProfileName,omitempty"`

	RoleName string `json:"roleName,omitempty"`

	RouteTableId string `json:"routeTableId,omitempty"`

	SecretAccessKey string `json:"secretAccessKey,omitempty"`

	SecurityGroupID string `json:"securityGroupID,omitempty"`

	SubnetId string `json:"subnetId,omitempty"`

	VpcId string `json:"vpcId,omitempty"`
}
