/*
 * Kubermatic API.
 *
 * Kubermatic API  This describes possible operations which can be made against the Kubermatic API.
 *
 * API version: 2.2.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package client

// AzureNodeSpec describes settings for an Azure node
type AzureNodeSpecV1 struct {

	// should the machine have a publicly accessible IP address
	AssignPublicIP bool `json:"assignPublicIP,omitempty"`

	// VM size
	Size string `json:"size"`

	// Additional metadata to set
	Tags map[string]string `json:"tags,omitempty"`
}
