/*
 * Kubermatic API.
 *
 * Kubermatic API  This describes possible operations which can be made against the Kubermatic API.
 *
 * API version: 2.2.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package client

// ClusterMetric defines a metric for the given cluster
type ClusterMetric struct {

	Name string `json:"name,omitempty"`

	Values []float64 `json:"values,omitempty"`
}
