/*
 * Kubermatic API.
 *
 * Kubermatic API  This describes possible operations which can be made against the Kubermatic API.
 *
 * API version: 2.2.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package client

type ClusterSpec struct {

	Cloud *CloudSpec `json:"cloud,omitempty"`

	ClusterNetwork *ClusterNetworkingConfig `json:"clusterNetwork,omitempty"`

	ComponentsOverride *ComponentSettings `json:"componentsOverride,omitempty"`

	// HumanReadableName is the cluster name provided by the user
	HumanReadableName string `json:"humanReadableName,omitempty"`

	// MasterVersion is Deprecated
	MasterVersion string `json:"masterVersion,omitempty"`

	// Pause tells that this cluster is currently not managed by the controller. It indicates that the user needs to do some action to resolve the pause.
	Pause bool `json:"pause,omitempty"`

	// PauseReason is the reason why the cluster is no being managed.
	PauseReason string `json:"pauseReason,omitempty"`

	// Version defines the wanted version of the control plane
	Version string `json:"version,omitempty"`
}
