/*
 * Kubermatic API.
 *
 * Kubermatic API  This describes possible operations which can be made against the Kubermatic API.
 *
 * API version: 2.2.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package client

// ClusterReqBody represents the body of a new cluster request
type ClusterReqBody struct {

	Cluster *ClusterSpec `json:"cluster,omitempty"`

	SshKeys []string `json:"sshKeys,omitempty"`
}
