/*
 * Kubermatic API.
 *
 * Kubermatic API  This describes possible operations which can be made against the Kubermatic API.
 *
 * API version: 2.2.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package client

type ClusterStatus struct {

	ApiserverCert *KeyCert `json:"apiserverCert,omitempty"`

	ApiserverSshKey *RsaKeys `json:"apiserverSshKey,omitempty"`

	// ErrorMessage contains a defauled error message in case the controller encountered an error. Will be reset if the error was resolved
	ErrorMessage string `json:"errorMessage,omitempty"`

	ErrorReason *ClusterStatusError `json:"errorReason,omitempty"`

	Health *ClusterHealth `json:"health,omitempty"`

	KubeletCert *KeyCert `json:"kubeletCert,omitempty"`

	LastUpdated *Time `json:"lastUpdated,omitempty"`

	// NamespaceName defines the namespace the control plane of this cluster is deployed in
	NamespaceName string `json:"namespaceName,omitempty"`

	Phase *ClusterPhase `json:"phase,omitempty"`

	RootCA *KeyCert `json:"rootCA,omitempty"`

	ServiceAccountKey *Bytes `json:"serviceAccountKey,omitempty"`

	// UserEmail contains the email of the owner of this cluster
	UserEmail string `json:"userEmail,omitempty"`

	// UserName contains the name of the owner of this cluster
	UserName string `json:"userName,omitempty"`
}
