/*
 * Kubermatic API.
 *
 * Kubermatic API  This describes possible operations which can be made against the Kubermatic API.
 *
 * API version: 2.2.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package client

type ComponentSettings struct {

	Apiserver *DeploymentSettings `json:"apiserver,omitempty"`

	ControllerManager *DeploymentSettings `json:"controllerManager,omitempty"`

	Etcd *EtcdSettings `json:"etcd,omitempty"`

	Scheduler *DeploymentSettings `json:"scheduler,omitempty"`
}
