/*
 * Kubermatic API.
 *
 * Kubermatic API  This describes possible operations which can be made against the Kubermatic API.
 *
 * API version: 2.2.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package client

type DatacenterSpec struct {

	Aws *AwsDatacenterSpec `json:"aws,omitempty"`

	Azure *AzureDatacenterSpec `json:"azure,omitempty"`

	Bringyourown *BringYourOwnDatacenterSpec `json:"bringyourown,omitempty"`

	Country string `json:"country,omitempty"`

	Digitalocean *DigitialoceanDatacenterSpec `json:"digitalocean,omitempty"`

	Hetzner *HetznerDatacenterSpec `json:"hetzner,omitempty"`

	Location string `json:"location,omitempty"`

	Openstack *OpenstackDatacenterSpec `json:"openstack,omitempty"`

	Provider string `json:"provider,omitempty"`

	Seed string `json:"seed,omitempty"`

	Vsphere *VSphereDatacenterSpec `json:"vsphere,omitempty"`
}
