/*
 * Kubermatic API.
 *
 * Kubermatic API  This describes possible operations which can be made against the Kubermatic API.
 *
 * API version: 2.2.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package client

type DigitaloceanSize struct {

	Available bool `json:"available,omitempty"`

	Disk int64 `json:"disk,omitempty"`

	Memory int64 `json:"memory,omitempty"`

	PriceHourly float64 `json:"price_hourly,omitempty"`

	PriceMonthly float64 `json:"price_monthly,omitempty"`

	Regions []string `json:"regions,omitempty"`

	Slug string `json:"slug,omitempty"`

	Transfer float64 `json:"transfer,omitempty"`

	Vcpus int64 `json:"vcpus,omitempty"`
}
