/*
 * Kubermatic API.
 *
 * Kubermatic API  This describes possible operations which can be made against the Kubermatic API.
 *
 * API version: 2.2.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package client

// DigitaloceanNodeSpec digitalocean node settings
type DigitaloceanNodeSpecV2 struct {

	// enable backups for the droplet
	Backups bool `json:"backups,omitempty"`

	// enable ipv6 for the droplet
	Ipv6 bool `json:"ipv6,omitempty"`

	// enable monitoring for the droplet
	Monitoring bool `json:"monitoring,omitempty"`

	// droplet size slug
	Size string `json:"size"`

	// additional droplet tags
	Tags []string `json:"tags,omitempty"`
}
