/*
 * Kubermatic API.
 *
 * Kubermatic API  This describes possible operations which can be made against the Kubermatic API.
 *
 * API version: 2.2.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package client

// ErrorDetails contains details about the error
type ErrorDetails struct {

	// The error code
	Code int64 `json:"code"`

	// The error message
	Message string `json:"message"`
}
