/*
 * Kubermatic API.
 *
 * Kubermatic API  This describes possible operations which can be made against the Kubermatic API.
 *
 * API version: 2.2.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package client

// See the client.authentiction.k8s.io API group for specifications of the exact input and output format
type ExecConfig struct {

	// Preferred input version of the ExecInfo. The returned ExecCredentials MUST use the same encoding version as the input.
	ApiVersion string `json:"apiVersion,omitempty"`

	// Arguments to pass to the command when executing it. +optional
	Args []string `json:"args,omitempty"`

	// Command to execute.
	Command string `json:"command,omitempty"`

	// Env defines additional environment variables to expose to the process. These are unioned with the host's environment, as well as variables client-go uses to pass argument to the plugin. +optional
	Env []ExecEnvVar `json:"env,omitempty"`
}
