/*
 * Kubermatic API.
 *
 * Kubermatic API  This describes possible operations which can be made against the Kubermatic API.
 *
 * API version: 2.2.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package client

type KeyCert struct {

	Cert *Bytes `json:"cert,omitempty"`

	Key *Bytes `json:"key,omitempty"`
}
