/*
 * Kubermatic API.
 *
 * Kubermatic API  This describes possible operations which can be made against the Kubermatic API.
 *
 * API version: 2.2.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package client

// Kubeconfig is a clusters kubeconfig
type Kubeconfig struct {

	// Legacy field from pkg/api/types.go TypeMeta. TODO(jlowdermilk): remove this after eliminating downstream dependencies. +optional
	ApiVersion string `json:"apiVersion,omitempty"`

	// Clusters is a map of referencable names to cluster configs
	Clusters []NamedCluster `json:"clusters,omitempty"`

	// Contexts is a map of referencable names to context configs
	Contexts []NamedContext `json:"contexts,omitempty"`

	// CurrentContext is the name of the context that you would like to use by default
	CurrentContext string `json:"current-context,omitempty"`

	// Extensions holds additional information. This is useful for extenders so that reads and writes don't clobber unknown fields +optional
	Extensions []NamedExtension `json:"extensions,omitempty"`

	// Legacy field from pkg/api/types.go TypeMeta. TODO(jlowdermilk): remove this after eliminating downstream dependencies. +optional
	Kind string `json:"kind,omitempty"`

	Preferences *Preferences `json:"preferences,omitempty"`

	// AuthInfos is a map of referencable names to user configs
	Users []NamedAuthInfo `json:"users,omitempty"`
}
