/*
 * Kubermatic API.
 *
 * Kubermatic API  This describes possible operations which can be made against the Kubermatic API.
 *
 * API version: 2.2.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package client

// MasterVersion describes a version of the master components
type MasterVersion struct {

	AllowedNodeVersions []string `json:"allowedNodeVersions,omitempty"`

	Default_ bool `json:"default,omitempty"`

	Version *Version `json:"version,omitempty"`
}
