/*
 * Kubermatic API.
 *
 * Kubermatic API  This describes possible operations which can be made against the Kubermatic API.
 *
 * API version: 2.2.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package client

// NamedCluster relates nicknames to cluster information
type NamedCluster struct {

	Cluster *Cluster `json:"cluster,omitempty"`

	// Name is the nickname for this Cluster
	Name string `json:"name,omitempty"`
}
