/*
 * Kubermatic API.
 *
 * Kubermatic API  This describes possible operations which can be made against the Kubermatic API.
 *
 * API version: 2.2.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package client

// NewClusterStatus defines the cluster status
type NewClusterStatus struct {

	// URL specifies the address at which the cluster is available
	Url string `json:"url,omitempty"`

	// Version actual version of the kubernetes master components
	Version string `json:"version,omitempty"`
}
