/*
 * Kubermatic API.
 *
 * Kubermatic API  This describes possible operations which can be made against the Kubermatic API.
 *
 * API version: 2.2.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package client

type NodeCloudSpecV2 struct {

	Aws *AwsNodeSpecV2 `json:"aws,omitempty"`

	Azure *AzureNodeSpecV1 `json:"azure,omitempty"`

	Digitalocean *DigitaloceanNodeSpecV2 `json:"digitalocean,omitempty"`

	Hetzner *HetznerNodeSpecV2 `json:"hetzner,omitempty"`

	Openstack *OpenstackNodeSpecV2 `json:"openstack,omitempty"`

	Vsphere *VSphereNodeSpecV2 `json:"vsphere,omitempty"`
}
