/*
 * Kubermatic API.
 *
 * Kubermatic API  This describes possible operations which can be made against the Kubermatic API.
 *
 * API version: 2.2.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package client

type NodeSystemInfoV2 struct {

	Architecture string `json:"architecture,omitempty"`

	ContainerRuntime string `json:"containerRuntime,omitempty"`

	ContainerRuntimeVersion string `json:"containerRuntimeVersion,omitempty"`

	KernelVersion string `json:"kernelVersion,omitempty"`

	KubeletVersion string `json:"kubeletVersion,omitempty"`

	OperatingSystem string `json:"operatingSystem,omitempty"`
}
