/*
 * Kubermatic API.
 *
 * Kubermatic API  This describes possible operations which can be made against the Kubermatic API.
 *
 * API version: 2.2.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package client

// NodeResources cpu and memory of a node
type NodeResourcesV2 struct {

	Cpu string `json:"cpu,omitempty"`

	Memory string `json:"memory,omitempty"`
}
