/*
 * Kubermatic API.
 *
 * Kubermatic API  This describes possible operations which can be made against the Kubermatic API.
 *
 * API version: 2.2.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package client

type NodeStatusV2 struct {

	// different addresses of a node
	Addresses []NodeAddressV2 `json:"addresses,omitempty"`

	Allocatable *NodeResourcesV2 `json:"allocatable,omitempty"`

	Capacity *NodeResourcesV2 `json:"capacity,omitempty"`

	// in case of a error this will contain a detailed error explanation
	ErrorMessage string `json:"errorMessage,omitempty"`

	// in case of a error this will contain a short error message
	ErrorReason string `json:"errorReason,omitempty"`

	// name of the actual Machine object
	MachineName string `json:"machineName,omitempty"`

	NodeInfo *NodeSystemInfoV2 `json:"nodeInfo,omitempty"`
}
