/*
 * Kubermatic API.
 *
 * Kubermatic API  This describes possible operations which can be made against the Kubermatic API.
 *
 * API version: 2.2.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package client

type OpenstackSubnet struct {

	// Id uniquely identifies the subnet
	Id string `json:"id,omitempty"`

	// Name is human-readable name for the subnet
	Name string `json:"name,omitempty"`
}
