/*
 * Kubermatic API.
 *
 * Kubermatic API  This describes possible operations which can be made against the Kubermatic API.
 *
 * API version: 2.2.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package client

// OpenstackNodeSpec openstack node settings
type OpenstackNodeSpecV2 struct {

	// instance flavor
	Flavor string `json:"flavor"`

	// image to use
	Image string `json:"image"`

	// Additional metadata to set
	Tags map[string]string `json:"tags,omitempty"`
}
