/*
 * Kubermatic API.
 *
 * Kubermatic API  This describes possible operations which can be made against the Kubermatic API.
 *
 * API version: 2.2.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package client

type OpenstackSize struct {

	// Disk is the amount of root disk, measured in GB
	Disk int64 `json:"disk,omitempty"`

	// IsPublic indicates whether the size is public (available to all projects) or scoped to a set of projects
	IsPublic bool `json:"isPublic,omitempty"`

	// Memory is the amount of memory, measured in MB
	Memory int64 `json:"memory,omitempty"`

	// Region specifies the geographic region in which the size resides
	Region string `json:"region,omitempty"`

	// Slug holds  the name of the size
	Slug string `json:"slug,omitempty"`

	// Swap is the amount of swap space, measured in MB
	Swap int64 `json:"swap,omitempty"`

	// VCPUs indicates how many (virtual) CPUs are available for this flavor
	Vcpus int64 `json:"vcpus,omitempty"`
}
