/*
 * Kubermatic API.
 *
 * Kubermatic API  This describes possible operations which can be made against the Kubermatic API.
 *
 * API version: 2.2.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package client

type OpenstackNetwork struct {

	// External set if network is the external network
	External bool `json:"external,omitempty"`

	// Id uniquely identifies the current network
	Id string `json:"id,omitempty"`

	// Name is the name of the network
	Name string `json:"name,omitempty"`
}
