/*
 * Kubermatic API.
 *
 * Kubermatic API  This describes possible operations which can be made against the Kubermatic API.
 *
 * API version: 2.2.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package client

type OpenstackTenant struct {

	// Id uniquely identifies the current tenant
	Id string `json:"id,omitempty"`

	// Name is the name of the tenant
	Name string `json:"name,omitempty"`
}
