/*
 * Kubermatic API.
 *
 * Kubermatic API  This describes possible operations which can be made against the Kubermatic API.
 *
 * API version: 2.2.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package client

type RsaKeys struct {

	PrivateKey *Bytes `json:"privateKey,omitempty"`

	PublicKey *Bytes `json:"publicKey,omitempty"`
}
