/*
 * Kubermatic API.
 *
 * Kubermatic API  This describes possible operations which can be made against the Kubermatic API.
 *
 * API version: 2.2.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package client

// SSHKeySpec represents the details of a ssh key
type SshKeySpec struct {

	Clusters []string `json:"clusters,omitempty"`

	Fingerprint string `json:"fingerprint,omitempty"`

	Name string `json:"name,omitempty"`

	Owner string `json:"owner,omitempty"`

	PublicKey string `json:"publicKey,omitempty"`
}
