/*
 * Kubermatic API.
 *
 * Kubermatic API  This describes possible operations which can be made against the Kubermatic API.
 *
 * API version: 2.2.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package client

type Status struct {

	// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources +optional
	ApiVersion string `json:"apiVersion,omitempty"`

	// Suggested HTTP return code for this status, 0 if not set. +optional
	Code int32 `json:"code,omitempty"`

	// continue may be set if the user set a limit on the number of items returned, and indicates that the server has more data available. The value is opaque and may be used to issue another request to the endpoint that served this list to retrieve the next set of available objects. Continuing a list may not be possible if the server configuration has changed or more than a few minutes have passed. The resourceVersion field returned when using this continue value will be identical to the value in the first response.
	Continue_ string `json:"continue,omitempty"`

	Details *StatusDetails `json:"details,omitempty"`

	// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds +optional
	Kind string `json:"kind,omitempty"`

	// A human-readable description of the status of this operation. +optional
	Message string `json:"message,omitempty"`

	Reason *StatusReason `json:"reason,omitempty"`

	// String that identifies the server's internal version of this object that can be used by clients to determine when objects have changed. Value must be treated as opaque by clients and passed unmodified back to the server. Populated by the system. Read-only. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#concurrency-control-and-consistency +optional
	ResourceVersion string `json:"resourceVersion,omitempty"`

	// selfLink is a URL representing this object. Populated by the system. Read-only. +optional
	SelfLink string `json:"selfLink,omitempty"`

	// Status of the operation. One of: \"Success\" or \"Failure\". More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#spec-and-status +optional
	Status string `json:"status,omitempty"`
}
