/*
 * Kubermatic API.
 *
 * Kubermatic API  This describes possible operations which can be made against the Kubermatic API.
 *
 * API version: 2.2.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package client

// StatusCause provides more information about an api.Status failure, including cases when multiple errors are encountered.
type StatusCause struct {

	// The field of the resource that has caused this error, as named by its JSON serialization. May include dot and postfix notation for nested attributes. Arrays are zero-indexed.  Fields may appear more than once in an array of causes due to fields having multiple errors. Optional.  Examples: \"name\" - the field \"name\" on the current resource \"items[0].name\" - the field \"name\" on the first array entry in \"items\" +optional
	Field string `json:"field,omitempty"`

	// A human-readable description of the cause of the error.  This field may be presented as-is to a reader. +optional
	Message string `json:"message,omitempty"`

	Reason *CauseType `json:"reason,omitempty"`
}
