/*
 * Kubermatic API.
 *
 * Kubermatic API  This describes possible operations which can be made against the Kubermatic API.
 *
 * API version: 2.2.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package client

// VSphereNodeSpec VSphere node settings
type VSphereNodeSpecV2 struct {

	Cpus int64 `json:"cpus,omitempty"`

	Memory int64 `json:"memory,omitempty"`

	Template string `json:"template,omitempty"`

	TemplateNetName string `json:"templateNetName,omitempty"`
}
