/*
 * Kubermatic API.
 *
 * Kubermatic API  This describes possible operations which can be made against the Kubermatic API.
 *
 * API version: 2.2.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package api

// AWSNodeSpec aws specific node settings
type AwsNodeSpecV2 struct {

	// ami to use. Will be defaulted to a ami for your selected operating system and region. Only set this when you know what you do.
	Ami string `json:"ami,omitempty"`

	// size of the volume in gb. Only one volume will be created
	DiskSize int64 `json:"diskSize"`

	InstanceType string `json:"instanceType"`

	// additional instance tags
	Tags map[string]string `json:"tags,omitempty"`

	VolumeType string `json:"volumeType"`
}
