/*
 * Kubermatic API.
 *
 * Kubermatic API  This describes possible operations which can be made against the Kubermatic API.
 *
 * API version: 2.2.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package api

type AzureSize struct {

	MaxDataDiskCount int32 `json:"maxDataDiskCount,omitempty"`

	MemoryInMB int32 `json:"memoryInMB,omitempty"`

	Name string `json:"name,omitempty"`

	NumberOfCores int32 `json:"numberOfCores,omitempty"`

	OsDiskSizeInMB int32 `json:"osDiskSizeInMB,omitempty"`

	ResourceDiskSizeInMB int32 `json:"resourceDiskSizeInMB,omitempty"`
}
