/*
 * Kubermatic API.
 *
 * Kubermatic API  This describes possible operations which can be made against the Kubermatic API.
 *
 * API version: 2.2.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package api

type AzureCloudSpec struct {

	AvailabilitySet string `json:"availabilitySet,omitempty"`

	ClientID string `json:"clientID,omitempty"`

	ClientSecret string `json:"clientSecret,omitempty"`

	ResourceGroup string `json:"resourceGroup,omitempty"`

	RouteTable string `json:"routeTable,omitempty"`

	SecurityGroup string `json:"securityGroup,omitempty"`

	Subnet string `json:"subnet,omitempty"`

	SubscriptionID string `json:"subscriptionID,omitempty"`

	TenantID string `json:"tenantID,omitempty"`

	Vnet string `json:"vnet,omitempty"`
}
