/*
 * Kubermatic API.
 *
 * Kubermatic API  This describes possible operations which can be made against the Kubermatic API.
 *
 * API version: 2.2.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package api

type CloudSpec struct {

	Aws *AwsCloudSpec `json:"aws,omitempty"`

	Azure *AzureCloudSpec `json:"azure,omitempty"`

	Bringyourown *BringYourOwnCloudSpec `json:"bringyourown,omitempty"`

	// DatacenterName where the users 'cloud' lives in.
	Dc string `json:"dc,omitempty"`

	Digitalocean *DigitaloceanCloudSpec `json:"digitalocean,omitempty"`

	Fake *FakeCloudSpec `json:"fake,omitempty"`

	Hetzner *HetznerCloudSpec `json:"hetzner,omitempty"`

	Openstack *OpenstackCloudSpec `json:"openstack,omitempty"`

	Vsphere *VSphereCloudSpec `json:"vsphere,omitempty"`
}
