/*
 * Kubermatic API.
 *
 * Kubermatic API  This describes possible operations which can be made against the Kubermatic API.
 *
 * API version: 2.2.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package api

// ClusterNetworkingConfig specifies the different networking parameters for a cluster.
type ClusterNetworkingConfig struct {

	// Domain name for services.
	DnsDomain string `json:"dnsDomain,omitempty"`

	Pods *NetworkRanges `json:"pods,omitempty"`

	Services *NetworkRanges `json:"services,omitempty"`
}
