/*
 * Kubermatic API.
 *
 * Kubermatic API  This describes possible operations which can be made against the Kubermatic API.
 *
 * API version: 2.2.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package api

type ClusterHealth struct {

	Apiserver bool `json:"apiserver,omitempty"`

	Controller bool `json:"controller,omitempty"`

	Etcd bool `json:"etcd,omitempty"`

	MachineController bool `json:"machineController,omitempty"`

	Scheduler bool `json:"scheduler,omitempty"`
}
