/*
 * Kubermatic API.
 *
 * Kubermatic API  This describes possible operations which can be made against the Kubermatic API.
 *
 * API version: 2.2.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package api

type ClusterAddress struct {

	// AdminToken is the token for the kubeconfig, the user can download
	AdminToken string `json:"adminToken,omitempty"`

	// ExternalName is the DNS name for this cluster
	ExternalName string `json:"externalName,omitempty"`

	// IP is the external IP under which the apiserver is available
	Ip string `json:"ip,omitempty"`

	// URL under which the Apiserver is available
	Url string `json:"url,omitempty"`
}
