/*
 * Kubermatic API.
 *
 * Kubermatic API  This describes possible operations which can be made against the Kubermatic API.
 *
 * API version: 2.2.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package api

// Context is a tuple of references to a cluster (how do I communicate with a kubernetes cluster), a user (how do I identify myself), and a namespace (what subset of resources do I want to work with)
type Context struct {

	// Cluster is the name of the cluster for this context
	Cluster string `json:"cluster,omitempty"`

	// Extensions holds additional information. This is useful for extenders so that reads and writes don't clobber unknown fields +optional
	Extensions []NamedExtension `json:"extensions,omitempty"`

	// Namespace is the default namespace to use on unspecified requests +optional
	Namespace string `json:"namespace,omitempty"`

	// AuthInfo is the name of the authInfo for this context
	User string `json:"user,omitempty"`
}
