/*
 * Kubermatic API.
 *
 * Kubermatic API  This describes possible operations which can be made against the Kubermatic API.
 *
 * API version: 2.2.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package api

// CreateClusterReqBody represents the request body for a create cluster request
type CreateClusterReqBody struct {

	Cluster *Cluster `json:"cluster,omitempty"`
}
