/*
 * Kubermatic API.
 *
 * Kubermatic API  This describes possible operations which can be made against the Kubermatic API.
 *
 * API version: 2.2.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package api

type DeploymentSettings struct {

	Replicas int32 `json:"replicas,omitempty"`

	Resources *ResourceRequirements `json:"resources,omitempty"`
}
