/*
 * Kubermatic API.
 *
 * Kubermatic API  This describes possible operations which can be made against the Kubermatic API.
 *
 * API version: 2.2.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package api

// ExecEnvVar is used for setting environment variables when executing an exec-based credential plugin.
type ExecEnvVar struct {

	Name string `json:"name,omitempty"`

	Value string `json:"value,omitempty"`
}
