/*
 * Kubermatic API.
 *
 * Kubermatic API  This describes possible operations which can be made against the Kubermatic API.
 *
 * API version: 2.2.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package api

// NamedExtension relates nicknames to extension information
type NamedExtension struct {

	Extension *RawExtension `json:"extension,omitempty"`

	// Name is the nickname for this Extension
	Name string `json:"name,omitempty"`
}
