/*
 * Kubermatic API.
 *
 * Kubermatic API  This describes possible operations which can be made against the Kubermatic API.
 *
 * API version: 2.2.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package api

// NamedContext relates nicknames to context information
type NamedContext struct {

	Context *Context `json:"context,omitempty"`

	// Name is the nickname for this Context
	Name string `json:"name,omitempty"`
}
