/*
 * Kubermatic API.
 *
 * Kubermatic API  This describes possible operations which can be made against the Kubermatic API.
 *
 * API version: 2.2.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package api

// NewSSHKeySpec represents the details of a ssh key
type NewSshKeySpec struct {

	Fingerprint string `json:"fingerprint,omitempty"`

	PublicKey string `json:"publicKey,omitempty"`
}
