/*
 * Kubermatic API.
 *
 * Kubermatic API  This describes possible operations which can be made against the Kubermatic API.
 *
 * API version: 2.2.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package api

// NewClusterSpec defines the cluster specification
type NewClusterSpec struct {

	Cloud *CloudSpec `json:"cloud,omitempty"`

	// Version desired version of the kubernetes master components
	Version string `json:"version,omitempty"`
}
