/*
 * Kubermatic API.
 *
 * Kubermatic API  This describes possible operations which can be made against the Kubermatic API.
 *
 * API version: 2.2.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package api

type NodeV2 struct {

	Metadata *ObjectMetaV2 `json:"metadata,omitempty"`

	Spec *NodeSpecV2 `json:"spec"`

	Status *NodeStatusV2 `json:"status,omitempty"`
}
