/*
 * Kubermatic API.
 *
 * Kubermatic API  This describes possible operations which can be made against the Kubermatic API.
 *
 * API version: 2.2.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package api

// NodeContainerRuntimeInfo information about the container runtime. Currently only \"cri-o\" and \"docker\" are supported
type NodeContainerRuntimeInfoV2 struct {

	Name string `json:"name,omitempty"`

	Version string `json:"version,omitempty"`
}
