/*
 * Kubermatic API.
 *
 * Kubermatic API  This describes possible operations which can be made against the Kubermatic API.
 *
 * API version: 2.2.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package api

// NodeSpec node specification
type NodeSpecV2 struct {

	Cloud *NodeCloudSpecV2 `json:"cloud"`

	OperatingSystem *OperatingSystemSpecV2 `json:"operatingSystem"`

	Versions *NodeVersionInfoV2 `json:"versions"`
}
