/*
 * Kubermatic API.
 *
 * Kubermatic API  This describes possible operations which can be made against the Kubermatic API.
 *
 * API version: 2.2.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package api

import (
	"time"
)

type ObjectMetaV2 struct {

	Annotations map[string]string `json:"annotations,omitempty"`

	// CreationTimestamp is a timestamp representing the server time when this object was created.
	CreationTimestamp time.Time `json:"creationTimestamp,omitempty"`

	// DeletionTimestamp is a timestamp representing the server time when this object was deleted.
	DeletionTimestamp time.Time `json:"deletionTimestamp,omitempty"`

	// The name to display in the frontend
	DisplayName string `json:"displayName,omitempty"`

	Labels map[string]string `json:"labels,omitempty"`

	// The unique name
	Name string `json:"name,omitempty"`
}
