/*
 * Kubermatic API.
 *
 * Kubermatic API  This describes possible operations which can be made against the Kubermatic API.
 *
 * API version: 2.2.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package api

type OpenstackCloudSpec struct {

	Domain string `json:"domain,omitempty"`

	FloatingIpPool string `json:"floatingIpPool,omitempty"`

	Network string `json:"network,omitempty"`

	Password string `json:"password,omitempty"`

	RouterID string `json:"routerID,omitempty"`

	SecurityGroups string `json:"securityGroups,omitempty"`

	SubnetID string `json:"subnetID,omitempty"`

	Tenant string `json:"tenant,omitempty"`

	Username string `json:"username,omitempty"`
}
