/*
 * Kubermatic API.
 *
 * Kubermatic API  This describes possible operations which can be made against the Kubermatic API.
 *
 * API version: 2.2.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package api

type OperatingSystemSpecV2 struct {

	Centos *CentOsSpec `json:"centos,omitempty"`

	ContainerLinux *ContainerLinuxSpecV2 `json:"containerLinux,omitempty"`

	Ubuntu *UbuntuSpecV2 `json:"ubuntu,omitempty"`
}
