/*
 * Kubermatic API.
 *
 * Kubermatic API  This describes possible operations which can be made against the Kubermatic API.
 *
 * API version: 2.2.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package api

// ProjectGroup is a helper data structure that stores the information about a project and a group prefix that a user belongs to
type ProjectGroup struct {

	Group string `json:"group,omitempty"`

	Id string `json:"id,omitempty"`
}
