/*
 * Kubermatic API.
 *
 * Kubermatic API  This describes possible operations which can be made against the Kubermatic API.
 *
 * API version: 2.2.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package api

// VSphereCredentials credentials represents a credential for accessing vSphere
type VSphereCredentials struct {

	Password string `json:"password,omitempty"`

	Username string `json:"username,omitempty"`
}
